{% set name = "requests" %}
{% set version = "2.23.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b3f43d496c6daba4493e7c431722aeb7dbc6288f52a6e04e7b6023b0247817e6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - certifi >=2017.4.17
    - chardet >=3.0.2,<4
    - idna >=2.5,<3
    - pip
    - python
    - urllib3 >=1.21.1,<1.26,!=1.25.0,!=1.25.1
  run:
    - certifi >=2017.4.17
    - chardet >=3.0.2,<4
    - idna >=2.5,<3
    - python
    - urllib3 >=1.21.1,<1.26,!=1.25.0,!=1.25.1

test:
  imports:
    - requests
  requires:
    - pysocks >=1.5.6,!=1.5.7
    - pytest >=3
    - pytest-cov
    - pytest-httpbin ==0.0.7
    - pytest-mock
    - pytest-xdist

about:
  home: "https://requests.readthedocs.io"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "Python HTTP for Humans."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
